// Generated by CoffeeScript 1.7.1
(function() {
  var ExchangeWrapper, Q;

  Q = require('q');

  module.exports = ExchangeWrapper = (function() {
    function ExchangeWrapper(exchange) {
      this.exchange = exchange;
      this.name = this.exchange.name;
    }

    ExchangeWrapper.prototype.publish = function(routingKey, message, options) {
      var def, _ref;
      def = Q.defer();
      if (!((_ref = this.exchange.options) != null ? _ref.confirm : void 0)) {
        this.exchange.publish(routingKey, message, options);
        def.resolve();
      } else {
        this.exchange.publish(routingKey, message, options, function(err) {
          if (err) {
            return def.reject(err);
          } else {
            return def.resolve();
          }
        });
      }
      return def.promise;
    };

    return ExchangeWrapper;

  })();

}).call(this);
