// Generated by CoffeeScript 1.7.1
(function() {
  var ExchangeWrapper, Q;

  Q = require('q');

  module.exports = ExchangeWrapper = (function() {
    function ExchangeWrapper(exchange) {
      this.exchange = exchange;
    }

    ExchangeWrapper.prototype.publish = function(routingKey, message, options) {
      var def;
      def = Q.defer();
      this.exchange.publish(routingKey, message, options, function(err) {
        if (err) {
          return def.reject(err);
        } else {
          return def.resolve();
        }
      });
      return def.promise;
    };

    ExchangeWrapper.prototype.bind = function() {};

    ExchangeWrapper.prototype.unbind = function() {};

    ExchangeWrapper.prototype.bind_headers = function() {};

    return ExchangeWrapper;

  })();

}).call(this);
