// Generated by CoffeeScript 1.6.3
(function() {
  var Rpc, amqpClient;

  amqpClient = require('./amqp-client');

  Rpc = new require('./rpc');

  module.exports = function(conf) {
    var amqpc, rpc;
    amqpc = amqpClient(conf);
    rpc = new Rpc(amqpc);
    return {
      exchange: amqpc.exchange,
      queue: amqpc.queue,
      bind: amqpc.bind,
      rpc: rpc.rpc,
      shutdown: amqpc.shutdown,
      local: amqpc.local
    };
  };

}).call(this);
