// Generated by CoffeeScript 1.7.1
(function() {
  var Rpc, RpcBackend, amqpClient;

  amqpClient = require('./amqp-client');

  Rpc = require('./rpc');

  RpcBackend = require('./rpc-backend');

  module.exports = function(conf) {
    var amqpc, rpc, rpcBackend;
    amqpc = amqpClient(conf);
    rpc = new Rpc(amqpc);
    rpcBackend = new RpcBackend(amqpc);
    return {
      exchange: amqpc.exchange,
      queue: amqpc.queue,
      bind: amqpc.bind,
      rpc: rpc.rpc,
      serve: rpcBackend.serve,
      shutdown: amqpc.shutdown,
      local: amqpc.local
    };
  };

}).call(this);
