// Generated by CoffeeScript 1.7.1
(function() {
  var __slice = [].slice;

  module.exports = function() {
    var k, o, os, t, v, _i, _len;
    t = arguments[0], os = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    for (_i = 0, _len = os.length; _i < _len; _i++) {
      o = os[_i];
      for (k in o) {
        v = o[k];
        if (v !== void 0) {
          t[k] = v;
        }
      }
    }
    return t;
  };

}).call(this);
