name: CI

on:
  push:

jobs:
  build:
    name: Create Docker image
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - uses: docker/login-action@v2
        with:
          registry: registry.a.tt.se
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Create build context
        run: docker context create builders

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          endpoint: builders

      - name: Build image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          tags: 'registry.a.tt.se/${{ github.repository }}:${{ github.ref_name }}'
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true

      - run: docker run --rm 'registry.a.tt.se/${{ github.repository }}:${{ github.ref_name }}' yarn ci-test
        name: Test image

      - run: docker push 'registry.a.tt.se/${{ github.repository }}:${{ github.ref_name }}'
        name: Push image
        if: ${{ contains(fromJson('["main", "master", "development"]'), github.ref_name) || github.ref_type == 'tag' }}



